-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clientes
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    nome character varying(60) NOT NULL,
    sobrenome character varying(60) NOT NULL,
    cpf character varying(11) NOT NULL,
    id_endereco bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contas
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    numero integer NOT NULL,
    saldo numeric(18, 2) NOT NULL DEFAULT 0,
    id_cliente bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.enderecos
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    logradouro character varying(60) NOT NULL,
    numero character varying(20) NOT NULL,
    complemento character varying(60),
    bairro character varying(60) NOT NULL,
    cidade character varying(60) NOT NULL,
    uf character(2) NOT NULL,
    pais character varying(60) NOT NULL,
    cep character varying(8) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.clientes
    ADD CONSTRAINT fk_cliente_endereco FOREIGN KEY (id_endereco)
    REFERENCES public.enderecos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contas
    ADD CONSTRAINT fk_conta_cliente FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

ALTER TABLE public.clientes DROP CONSTRAINT fk_cliente_endereco;

ALTER TABLE public.clientes DROP COLUMN id_endereco;

CREATE TABLE IF NOT EXISTS public.rel_clientes_enderecos
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    id_cliente bigint NOT NULL,
    id_endereco bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.rel_clientes_enderecos
    ADD CONSTRAINT fk_clientes_enderecos_clientes FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_clientes_enderecos
    ADD CONSTRAINT fk_clientes_enderecos_enderecos FOREIGN KEY (id_endereco)
    REFERENCES public.enderecos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


INSERT INTO clientes (nome, sobrenome, cpf) VALUES ('Fernando', 'Back', '123');
INSERT INTO clientes (nome, sobrenome, cpf) VALUES ('Maricleide', 'Santiago', '456');

INSERT INTO enderecos (logradouro, numero, complemento, bairro, cidade, uf, pais, cep)
VALUES ('rua xyz', '120', 'casa verde', 'centro', 'joinville', 'sc', 'brasil', '88777111');
INSERT INTO enderecos (logradouro, numero, complemento, bairro, cidade, uf, pais, cep)
VALUES ('rua da praia', '50', 'casa amarela', 'meia praia', 'itapema', 'sc', 'brasil', '88666222');

INSERT INTO rel_clientes_enderecos (id_cliente, id_endereco) VALUES (1, 1);
INSERT INTO rel_clientes_enderecos (id_cliente, id_endereco) VALUES (2, 1);
INSERT INTO rel_clientes_enderecos (id_cliente, id_endereco) VALUES (2, 2);