-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.musicas
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    titulo character varying(120) NOT NULL,
    duracao_segundos integer NOT NULL,
    id_album bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    username character varying(120) NOT NULL,
    nome character varying(120) NOT NULL,
    sobrenome character varying(120) NOT NULL,
    email character varying(120) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.albuns
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    titulo character varying(120) NOT NULL,
    id_artista bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.artistas
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    nome character varying(120) NOT NULL,
    nacionalidade character varying(120) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.generos
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    titulo character varying(120) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.playlists
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    titulo character varying(120) NOT NULL,
    descricao character varying(500),
    id_usuario bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reproducoes
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    id_usuario bigint NOT NULL,
    id_musica bigint NOT NULL,
    hora_reproducao timestamp without time zone NOT NULL,
    qtd_segundos_reproduzidos integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.interpretes
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    id_artista bigint NOT NULL,
    id_musica bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rel_playlists_musicas
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    id_playlist bigint NOT NULL,
    id_musica bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rel_generos_musicas
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    id_genero bigint NOT NULL,
    id_musica bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rel_generos_albuns
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    id_genero bigint NOT NULL,
    id_album bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rel_generos_artistas
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    id_genero bigint NOT NULL,
    id_artista bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.curtidas
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    id_usuario bigint NOT NULL,
    id_musica bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.musicas
    ADD CONSTRAINT fk_musicas_albuns FOREIGN KEY (id_album)
    REFERENCES public.albuns (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.albuns
    ADD CONSTRAINT fk_albuns_artistas FOREIGN KEY (id_artista)
    REFERENCES public.artistas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.playlists
    ADD CONSTRAINT fk_playlists_usuarios FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.reproducoes
    ADD CONSTRAINT fk_reproducoes_usuarios FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.reproducoes
    ADD CONSTRAINT fk_reproducoes_musicas FOREIGN KEY (id_musica)
    REFERENCES public.musicas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.interpretes
    ADD CONSTRAINT fk_interpretes_artistas FOREIGN KEY (id_artista)
    REFERENCES public.artistas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.interpretes
    ADD CONSTRAINT fk_interpretes_musicas FOREIGN KEY (id_musica)
    REFERENCES public.musicas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_playlists_musicas
    ADD CONSTRAINT fk_rel_p_m_playlists FOREIGN KEY (id_playlist)
    REFERENCES public.playlists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_playlists_musicas
    ADD CONSTRAINT fk_rel_p_m_musicas FOREIGN KEY (id_musica)
    REFERENCES public.musicas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_generos_musicas
    ADD CONSTRAINT fk_rel_g_m_generos FOREIGN KEY (id_genero)
    REFERENCES public.generos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_generos_musicas
    ADD CONSTRAINT fk_g_m_musicas FOREIGN KEY (id_musica)
    REFERENCES public.musicas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_generos_albuns
    ADD CONSTRAINT fk_rel_g_alb_generos FOREIGN KEY (id_genero)
    REFERENCES public.generos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_generos_albuns
    ADD CONSTRAINT fk_rel_g_alb_albuns FOREIGN KEY (id_album)
    REFERENCES public.albuns (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_generos_artistas
    ADD CONSTRAINT fk_rel_g_art_generos FOREIGN KEY (id_genero)
    REFERENCES public.generos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_generos_artistas
    ADD CONSTRAINT fk_rel_g_art_artistas FOREIGN KEY (id_artista)
    REFERENCES public.artistas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.curtidas
    ADD CONSTRAINT fk_curtidas_usuarios FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.curtidas
    ADD CONSTRAINT fk_curtidas_musicas FOREIGN KEY (id_musica)
    REFERENCES public.musicas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;